### ISSUE TITLE
error with 'from oeel import oeel'

### ISSUE THREAD

**Issue by Dushuai12138** [open-geocomputing/OpenEarthEngineLibrary#21]
windows 10
python3.11
oeel                      0.9.8.6                  pypi_0    pypi
'''
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[25], line 1
----> 1 from oeel import oeel

File E:\ProgramData\Anaconda3\envs\gee1\Lib\site-packages\oeel\oeel.py:17
     14 from shutil import which
     16 from . import external
---> 17 from . import colab
     18 oeelLibPath=os.path.dirname(__file__)
     20 class oeelMissingExternalCommand(Exception):

File E:\ProgramData\Anaconda3\envs\gee1\Lib\site-packages\oeel\colab.py:3
      1 import ee
      2 import IPython
----> 3 from google.colab import output
      4 from google.oauth2.credentials import Credentials
      5 from datetime import datetime, timedelta

File E:\ProgramData\Anaconda3\envs\gee1\Lib\site-packages\google\colab\__init__.py:23
     21 from google.colab import _installation_commands
     22 from google.colab import _shell_customizations
---> 23 from google.colab import _system_commands
     24 from google.colab import _tensorflow_magics
     25 from google.colab import auth

File E:\ProgramData\Anaconda3\envs\gee1\Lib\site-packages\google\colab\_system_commands.py:24
     22 import locale
     23 import os
---> 24 import pty
     25 import select
     26 import signal

File E:\ProgramData\Anaconda3\envs\gee1\Lib\pty.py:12
     10 import os
     11 import sys
---> 12 import tty
     14 # names imported directly for test mocking purposes
     15 from os import close, waitpid

File E:\ProgramData\Anaconda3\envs\gee1\Lib\tty.py:5
      1 """Terminal utilities."""
      3 # Author: Steen Lumholt.
----> 5 from termios import *
      7 __all__ = ["setraw", "setcbreak"]
      9 # Indexes for termios list.

ModuleNotFoundError: No module named 'termios'
'''

**Comment by mgravey** [comment]
I will update later today the package, the feature causing the crash is not needed anymore so I will just remove it.

**Comment by mgravey** [comment]
If urgent, I corrected the package and you can download it from this repo (https://github.com/open-geocomputing/OpenEarthEngineLibrary/tree/oeel-python), and install it manually

**Comment by Dushuai12138** [comment]
thank you so much! That is very helpful.

**Comment by mgravey** [comment]
it should be fixed by now

**Comment by Dushuai12138** [comment]
I have installed the oeel-0.9.8.7, and I run ```from oeel import oeel```, it reports :
```
Start initilization of OEEL...
---------------------------------------------------------------------------
oeelMissingExternalCommand                Traceback (most recent call last)
Cell In[4], line 1
----> 1 from oeel import oeel

File E:\ProgramData\Anaconda3\envs\gee1\Lib\site-packages\oeel\oeel.py:73
     70 		open(oeelLibPath+'/initialized', 'a').close()
     71 		print('Initilization of OEEL is finished')
---> 73 initialize()
     76 class oeelParentDirectory(dict):
     78 	__getattr__ = dict.get

File E:\ProgramData\Anaconda3\envs\gee1\Lib\site-packages\oeel\oeel.py:40, in initialize()
     38 	raise oeelMissingExternalCommand('git is required for this module please install it, and if needed add it to the path.')
     39 if(not nodePath):
---> 40 	raise oeelMissingExternalCommand('node(NodeJS) is required for this module please install it, and if needed add it to the path.')
     41 if gitPath:
     42 	os.chdir(oeelLibPath)

oeelMissingExternalCommand: node(NodeJS) is required for this module please install it, and if needed add it to the path.
```
I also install nodejs-0.1.1, and add it to user's and system's variables. the error still exists.

**Comment by mgravey** [comment]
Where did you find node 0.1.1 ?? we are at version 22 currently, I suppose you install the wrong stuff.
look here: https://nodejs.org/en

**Comment by Dushuai12138** [comment]
thanks. now I also encounter with next problem[#22 ](https://github.com/open-geocomputing/OpenEarthEngineLibrary/issues/22)
